#These constants point to subprograms
#
from commandrouter_length_of_commandtypes import *
from commandrouter_own_commands import *
#
commandtypes={"m":ct_m,                                         #and devicetype :)
            "l" :ct_m,
            "c" :ct_m,
            "r" :ct_m,
            "h" :ct_m,
            "p" :ct_m,
            "q" :ct_m,
            "oc":ct_oc,
            "od":ct_od,
            "ac":ct_ac,
            "ad":ct_ad,
            "ic":ct_ic,
            "id":ct_id,
            "nc":ct_nc,
            "or":ct_or,
            "rr":ct_or,
            "os":ct_os,
            "rs":ct_os,
            "ot":ct_ot,
            "rt":ct_ot,
            "ou":ct_ou,
            "ru":ct_ou,
            "ar":ct_ar,
            "sr":ct_ar,
            "as":ct_as,
            "ss":ct_as,
            "at":ct_as,
            "st":ct_as,
            "au":ct_au,
            "su":ct_au,
            "oo":ct_oo,
            "ro":ct_oo,
            "op":ct_op,
            "rp":ct_op,
            "oq":ct_oq,
            "rq":ct_oq,
            "ap":ct_ap,
            "sp":ct_ap,
            "om":ct_om,
            "rm":ct_om,
            "on":ct_on,
            "rn":ct_on,
            "oa":ct_oa,
            "ra":ct_oa,
            "of":ct_of,
            "rf":ct_of,
            "ob":ct_ob,
            "rb":ct_ob,
            "am":ct_am,
            "sm":ct_am,
            "an":ct_an,
            "sn":ct_an,
            "af":ct_af,
            "sf":ct_af,
            "aa":ct_aa,
            "sa":ct_aa,
            "ab":ct_ab,
            "sb":ct_ab
}
#
command={0x0 : com0,
        0xf0 : com240,
        0xfc : com252,
        0xfd : com253,
        0xfe : com254,
        0xff : com255,
        0xfff0 : com240,
        0xfffc : com252,
        0xfffd : com253,
        0xfffe : com254,
        0xffff : com255,
        0xfffffff0 : com240,
        0xfffffffc : com252,
        0xfffffffd : com253,
        0xfffffffe : com254,
        0xffffffff : com255,
}
#
length_of_par={"a" : 1,
        "b" : 1,
        "i" : 2,
        "w" : 2,
        "e" : 4,
        "L" : 4,
        "s" : 4,
        "t" : 8,
        "d" : 8,
}
#